### ISSUE TITLE
【大佬求助】签名导出ipa报错，以及签名注入动态库报错

### ISSUE THREAD

**Issue by 1904458866** [DargonLee/EasySignIpa#4]
签名导出报错
cloud@Baiyun IOSTEST % esign -s /Users/cloud/Desktop/IOSTEST/CPU-x/CPU-x_1.6.7_01191821_Crack.ipa -o /Users/cloud/Downloads     
✅ prepare app
[-]prepare: current_path => /Users/cloud/Desktop/IOSTEST
[-]prepare: AppPath => /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmp1mtzlxkc/Payload/ARMCPUZ.app
[-]prepare info_plist_file_path => : /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmp1mtzlxkc/Payload/ARMCPUZ.app/Info.plist
[-]prepare frameworks_dir => : /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmp1mtzlxkc/Payload/ARMCPUZ.app/Frameworks
[-]prepare plugins_dir => : /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmp1mtzlxkc/Payload/ARMCPUZ.app/PlugIns
[-]prepare target_app_path => : /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmp1mtzlxkc/Payload/ARMCPUZ.app
[-]prepare tempdir => : /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmp1mtzlxkc
✅ resign info
[-]resign: AppName: ARMCPUZ.app
[-]cms embedded done
👉🏻 begin codesigning frameworks
👉🏻 begin codesigning app
[-]AppPath => /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmp1mtzlxkc/Payload/ARMCPUZ.app
[-]CodesigningIdentity => 685B5A19A5BCEA18EEB9974200BEDCA5DC827C3A
/var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmp1mtzlxkc/Payload/ARMCPUZ.app: replacing existing signature
✅ zip app to ipa
zip: payload_path /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmp1mtzlxkc/Payload/ARMCPUZ.app
zip: tempdir /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmp1mtzlxkc
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/esign", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/esign/cli.py", line 67, in main
    esign_obj.resign(app_path, inject_dylib_list, output_path, install_type)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/esign/esign.py", line 169, in resign
    self._zip_app()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/esign/esign.py", line 310, in _zip_app
    shutil.copytree(self.target_app_path, payload_app_path)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 559, in copytree
    with os.scandir(src) as itr:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmp1mtzlxkc/Payload/ARMCPUZ.app'

签名注入报错
cloud@Baiyun IOSTEST % esign -s /Users/cloud/Desktop/IOSTEST/砸壳IPA存放/CPU-x/CPU-x_1.6.7_01191821_Crack.ipa -l /Users/cloud/Desktop/IOSTEST/dylib/TESTTZDS.dylib   
✅ prepare app
[-]prepare: current_path => /Users/cloud/Desktop/IOSTEST
[-]prepare: AppPath => /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmpxzgb7xme/Payload/ARMCPUZ.app
[-]prepare info_plist_file_path => : /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmpxzgb7xme/Payload/ARMCPUZ.app/Info.plist
[-]prepare frameworks_dir => : /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmpxzgb7xme/Payload/ARMCPUZ.app/Frameworks
[-]prepare plugins_dir => : /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmpxzgb7xme/Payload/ARMCPUZ.app/PlugIns
[-]prepare target_app_path => : /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmpxzgb7xme/Payload/ARMCPUZ.app
[-]prepare tempdir => : /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmpxzgb7xme
✅ resign info
[-]resign: AppName: ARMCPUZ.app
[-]cms embedded done
✅ inject dylib
[-]dylibs => ['/Users/cloud/Desktop/IOSTEST/dylib/TESTTZDS.dylib']
[-]Info.plist path => /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmpxzgb7xme/Payload/ARMCPUZ.app/Info.plist
[-]inject dylib => TESTTZDS
[-]execu_table_path => /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmpxzgb7xme/Payload/ARMCPUZ.app/ARMCPUZ
[-]app_frameworks_path => /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmpxzgb7xme/Payload/ARMCPUZ.app/Frameworks
[-]dylib_framework_path => /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmpxzgb7xme/Payload/ARMCPUZ.app/Frameworks/TESTTZDS.dylib
👉🏻 begin optool inject
[-]optool_cmd => /Users/cloud/.esign/bin/optool install -c load -p "@executable_path/Frameworks/TESTTZDS.dylib" -t /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmpxzgb7xme/Payload/ARMCPUZ.app/ARMCPUZ
Found thin header...
Inserting a LC_LOAD_DYLIB command for architecture: arm64
Successfully inserted a LC_LOAD_DYLIB command for arm64
Writing executable to /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmpxzgb7xme/Payload/ARMCPUZ.app/ARMCPUZ...
👉🏻 begin codesigning frameworks
👉🏻 begin codesigning app
[-]AppPath => /var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmpxzgb7xme/Payload/ARMCPUZ.app
[-]CodesigningIdentity => 685B5A19A5BCEA18EEB9974200BEDCA5DC827C3A
/var/folders/3g/s9mvy55579n8qmm0ftlfkl7c0000gn/T/tmpxzgb7xme/Payload/ARMCPUZ.app: object file format unrecognized, invalid, or unsuitable
✅ app info
[-]BundleName => ARMCPUZ
[-]BundleID => com.benchu.ARMCPUZ.muz
[-]ShortVersion => 1.6.7
[-]ExecutableName => ARMCPUZ

**Comment by nerocho** [comment]
我和你一样的错误，你有解决吗
